<a href="https://colab.research.google.com/github/lodowd/statsintro/blob/master/torch_dl_tutorial_uw_madison.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

In [ ]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Check PyTorch version
print(f"PyTorch version: {torch.__version__}")

# Check if MPS is available and set the device accordingly
if torch.backends.mps.is_available():
    device = torch.device("mps")
    print("MPS is available. Using MPS as device.")
else:
    device = torch.device("cpu")
    print("MPS is not available. Using CPU as device.")

# Placeholder code for using NumPy, Pandas, and Matplotlib (if needed)
# Example: Create a NumPy array
np_array = np.random.rand(5, 5)
print("NumPy Array:\n", np_array)

# Example: Create a Pandas DataFrame
df = pd.DataFrame(np_array, columns=["A", "B", "C", "D", "E"])




PyTorch version: 2.4.1+cu121
MPS is not available. Using CPU as device.
NumPy Array:
 [[0.32359338 0.71268216 0.48517893 0.50599654 0.35672933]
 [0.16629256 0.02253387 0.58387649 0.62372084 0.98050528]
 [0.07319635 0.74662045 0.30083377 0.32822186 0.41510542]
 [0.26160418 0.04825092 0.52321335 0.77861569 0.70866998]
 [0.56816619 0.97189398 0.17551147 0.06243787 0.51861007]]


In [ ]:
print(torch.cuda.is_available())

False


In [ ]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
scalar.item()

7

In [ ]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
matrix = torch.tensor([1,2],
                        [3,4])
matrix

TypeError: tensor() takes 1 positional argument but 2 were given

In [ ]:
matrix.shape

torch.Size([2])

In [ ]:
matrix.ndim

1

In [ ]:
matrix[1]

In [ ]:
tensor = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]])
tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.3003, 0.3236, 0.7256, 0.2041],
        [0.5878, 0.1208, 0.9647, 0.3084],
        [0.2865, 0.0721, 0.3387, 0.4514]])

In [ ]:
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor

tensor([[[0.1098, 0.3851, 0.0407],
         [0.2776, 0.7693, 0.5828],
         [0.1009, 0.4968, 0.2984],
         ...,
         [0.8293, 0.1624, 0.3435],
         [0.0663, 0.3425, 0.7849],
         [0.1387, 0.5013, 0.2142]],

        [[0.4946, 0.9302, 0.9975],
         [0.0906, 0.3248, 0.7150],
         [0.1924, 0.9881, 0.2304],
         ...,
         [0.7622, 0.1659, 0.4536],
         [0.1383, 0.9647, 0.0877],
         [0.0813, 0.8838, 0.8405]],

        [[0.3933, 0.5546, 0.9893],
         [0.5247, 0.6904, 0.5522],
         [0.3164, 0.9171, 0.6787],
         ...,
         [0.9580, 0.0186, 0.7900],
         [0.4442, 0.5255, 0.2974],
         [0.5039, 0.4061, 0.0820]],

        ...,

        [[0.5138, 0.9916, 0.1348],
         [0.1724, 0.3880, 0.4265],
         [0.7295, 0.2375, 0.0424],
         ...,
         [0.3631, 0.3137, 0.2309],
         [0.1171, 0.3857, 0.7425],
         [0.4978, 0.2537, 0.7541]],

        [[0.3465, 0.0134, 0.0561],
         [0.5756, 0.9298, 0.4340],
         [0.

In [ ]:
ones = torch.ones(size=(3,3))
ones

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

In [ ]:
float_32_tensor = torch.tensor([3.0, 2.0, 9.0],
                               dtype=torch.float32,  # Explicitly setting dtype as float32
                               device=None,  # This can be omitted or set to a specific device
                               requires_grad=False)  # 'False' should be capitalized

float_32_tensor

tensor([3., 2., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_32_tensor.type(torch.float16)

tensor([3., 2., 9.], dtype=torch.float16)

In [ ]:
tesnor = torch.tensor([1,2,3])
tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
tensor + 10

tensor([[[11, 12, 13],
         [14, 15, 16],
         [17, 18, 19]]])

In [ ]:
torch.matmul(tensor, tensor)

tensor([[[ 30,  36,  42],
         [ 66,  81,  96],
         [102, 126, 150]]])

In [ ]:
tensor @ tensor

tensor([[[ 30,  36,  42],
         [ 66,  81,  96],
         [102, 126, 150]]])

In [ ]:
tensor = torch.tensor([[1,2,3,4,5], [1,2,3,4,5]])
tensor

tensor([[1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5]])

In [ ]:
tensor.T

tensor([[1, 1],
        [2, 2],
        [3, 3],
        [4, 4],
        [5, 5]])

In [ ]:
import matplotlib.pyplot as plt
import numpy as np
import torch
from torch import nn
from pathlib import Path

torch.__version__

'2.4.1+cu121'

In [ ]:
weight = 0.7
bias = 0.3

start = 0
end = 1

step = 0.02

X = torch.arange(start, end, step).unsqueeze(dim=1)
Y = weight * X + bias
X[:10], Y[:10]

(tensor([[0.0000],
         [0.0200],
         [0.0400],
         [0.0600],
         [0.0800],
         [0.1000],
         [0.1200],
         [0.1400],
         [0.1600],
         [0.1800]]),
 tensor([[0.3000],
         [0.3140],
         [0.3280],
         [0.3420],
         [0.3560],
         [0.3700],
         [0.3840],
         [0.3980],
         [0.4120],
         [0.4260]]))

In [ ]:
len(X), len(Y)

(50, 50)

In [ ]:
train_split = int(0.8*len(X))
X_train, Y_train = X[:train_split], Y[:train_split]
X_test, Y_test = X[train_split:], Y[train_split:]

len(X_test), len(Y_test), len(X_train), len(Y_train)

(10, 10, 40, 40)

In [ ]:
import matplotlib.pyplot as plt

def plot_predictions(training_data=None, train_labels=None,
                     test_data=None, test_labels=None, predictions=None):
    plt.figure(figsize=[10, 7])

    # Plot the training data
    plt.scatter(training_data, train_labels, c="b", s=10, label="Training Data")

    # Plot the testing data
    plt.scatter(test_data, test_labels, c="g", s=10, label="Testing Data")

    # Plot the predictions if provided
    if predictions is not None:
        plt.scatter(test_data, predictions, c="r", s=10, label="Predictions")

    # Add legend with size specified in a dictionary
    plt.legend(prop={'size': 14})
    plt.show()


In [ ]:
import torch
import torch.nn as nn

class LinearRegressionModel(nn.Module):  # Fix capitalization
    def __init__(self):
        super().__init__()
        # Define the model parameters (weights and bias)
        self.weights = nn.Parameter(torch.rand(1, requires_grad=True, dtype=torch.float32))  # Fixed typo in torch.rand
        self.bias = nn.Parameter(torch.rand(1, requires_grad=True, dtype=torch.float32))  # Fixed typo

    def forward(self, x: torch.Tensor) -> torch.Tensor:  # Fix the comma
        # Linear regression: y = wx + b
        return self.weights * x + self.bias


In [ ]:
model_0.state_dict()

In [ ]:
# Ensure correct context manager usage with parentheses
with torch.inference_mode():
    y_preds = model_0(X_test)  # Consistent naming (y_preds)

# Call the plot_predictions function with the correct argument
plot_predictions(predictions=y_preds)


NameError: name 'model_0' is not defined

In [ ]:
loss_fn = nn.L1loss()

optimizer = torch.optim.SGD(params=model_0.parameters(), lr=0.1)

AttributeError: module 'torch.nn' has no attribute 'L1loss'

In [ ]:
torch.manual_seed(42)

epochs = 200

epoch_count = []
train_loss_values = []
test_loss_values = []

for epoch in range(epochs):
  model_0.train()

  y_pred = model_0(X_train)

  loss = loss_fn(Y_pred, Y_train)

  optimizer.zero_grad()

  loss.backward()

  optimizer.step()

  model_0.eval()

  with torch.inference_mode():
    test_pred = model_0(X_test)
    test_loss = loss_fn(test_pred, y_test)

  epoch_count.append(epoch)
  train_loss_values.append(loss.detech().numpy())
  test_loss_values.append(test_loss.detch().numpy())
  print()



NameError: name 'model_0' is not defined

In [ ]:
model_0.state_dict()

In [ ]:
with torch.inference_mode():
  y_preds_new = model_0(X_test)

In [ ]:
plt.plot(epoch_count, np.array(torch.tensor(train_loss_values),cpu().numpy()),
          label="Train Loss")
plt.plot(epoch_count, test_loss_values, label="Test Loss")
plt.title("training and Test Loss Curves")
plt.ylabel("loss"
plot.xlabel())


In [ ]:
epoch_count = np.array